/**
 * SolidWorks Macro Export — generates a .swb (VBScript-style) macro file
 * that creates a new Part with a 2D sketch containing joints, links, and outlines.
 *
 * The generated macro uses the SolidWorks API with late binding (Object types)
 * so it runs from Tools > Macro > Run without additional references.
 *
 * SolidWorks API always uses meters internally for coordinate arguments,
 * regardless of the document's display unit setting.
 *
 * World units: 25 world units = 1 cm = 10 mm → 1 world unit = 0.0004 m.
 */

import type { Joint, Link, Body, Outline, SliderConstraint, ColliderConstraint } from '../types';
import { computeBodyTransform, localToWorld } from '../core/body-transform';
import type { ExportUnit } from './export-manager';

/** World-to-meters scale (SolidWorks API always uses meters). */
const W2M = 0.0004;

/** Joint circle radius in meters (annotation size). */
const JOINT_RADIUS_M = 0.0015;  // 1.5mm
const FIXED_JOINT_RADIUS_M = 0.002; // 2.0mm

/** Format a number for VBA: 6 significant digits, always has a decimal point. */
function f(v: number): string {
  // Ensure 0 is output as "0#" (VBA double literal)
  if (v === 0) return '0#';
  return v.toPrecision(6) + '#';
}

export function exportSolidWorksMacro(
  joints: Record<string, Joint>,
  links: Record<string, Link>,
  bodies: Record<string, Body>,
  baseBodyId: string,
  outlines: Record<string, Outline>,
  sliders: Record<string, SliderConstraint>,
  colliders: Record<string, ColliderConstraint>,
  showLinksGlobal: boolean = true,
  _unit: ExportUnit = 'mm',
): string {
  const lines: string[] = [];
  const emit = (s: string) => lines.push(s);

  const bodyList = Object.values(bodies);

  // ==================== MACRO HEADER ====================
  emit("' =====================================================");
  emit("' SolidWorks Sketch Macro — generated by Linkage Studio");
  emit("' Opens a new Part, creates a sketch on the Front Plane,");
  emit("' and draws the mechanism's joints, links, and outlines.");
  emit("' Run via: Tools > Macro > Run  (select this .swb file)");
  emit("' =====================================================");
  emit('');
  emit('Dim swApp As Object');
  emit('Dim Part As Object');
  emit('Dim SketchMgr As Object');
  emit('Dim boolstatus As Boolean');
  emit('');
  emit('Sub main()');
  emit('    Set swApp = Application.SldWorks');
  emit('');
  emit("    ' Create a new Part using the default template");
  emit('    Dim templatePath As String');
  emit('    templatePath = swApp.GetUserPreferenceStringValue(9)'); // 9 = swDefaultTemplatePart
  emit('    If templatePath = "" Then');
  emit('        templatePath = swApp.GetUserPreferenceStringValue(25)'); // fallback
  emit('    End If');
  emit('    Set Part = swApp.NewDocument(templatePath, 0, 0, 0)');
  emit('    If Part Is Nothing Then');
  emit('        MsgBox "Could not create new part. Check your default template in Tools > Options > Default Templates."');
  emit('        Exit Sub');
  emit('    End If');
  emit('');

  // Note about units
  emit(`    ' Note: Sketch coordinates are in meters (SolidWorks API convention).`);
  emit(`    ' Document display units can be changed in Tools > Options > Document Properties > Units.`);

  emit('');
  emit("    ' Select Front Plane");
  emit('    boolstatus = Part.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)');
  emit('');
  emit('    Set SketchMgr = Part.SketchManager');
  emit('    SketchMgr.InsertSketch True');
  emit('');

  // ==================== JOINTS (circles) ====================
  emit("    ' ==================== JOINTS ====================");
  for (const body of bodyList) {
    for (const jid of body.jointIds) {
      const j = joints[jid];
      if (!j || j.hidden) continue;
      const x = j.position.x * W2M;
      const y = -j.position.y * W2M; // flip Y: screen-down → CAD-up
      const r = j.type === 'fixed' ? FIXED_JOINT_RADIUS_M : JOINT_RADIUS_M;
      const label = j.label || jid.slice(0, 8);
      emit(`    ' Joint "${label}" (${j.type})`);
      emit(`    SketchMgr.CreateCircleByRadius ${f(x)}, ${f(y)}, 0#, ${f(r)}`);
    }
  }
  emit('');

  // ==================== LINKS (construction lines) ====================
  if (showLinksGlobal) {
    emit("    ' ==================== LINKS ====================");
    for (const link of Object.values(links)) {
      const jA = joints[link.jointIds[0]];
      const jB = joints[link.jointIds[1]];
      if (!jA || !jB || jA.hidden || jB.hidden) continue;

      let owningBody: Body | null = null;
      for (const body of bodyList) {
        if (body.id === baseBodyId) continue;
        if (body.jointIds.includes(link.jointIds[0]) && body.jointIds.includes(link.jointIds[1])) {
          owningBody = body;
          break;
        }
      }
      if (!owningBody || !owningBody.showLinks) continue;

      const x1 = jA.position.x * W2M;
      const y1 = -jA.position.y * W2M;
      const x2 = jB.position.x * W2M;
      const y2 = -jB.position.y * W2M;

      emit(`    ' Link on body "${owningBody.name}"`);
      emit(`    SketchMgr.CreateLine ${f(x1)}, ${f(y1)}, 0#, ${f(x2)}, ${f(y2)}, 0#`);
    }
    emit('');
  }

  // ==================== OUTLINES (closed polylines) ====================
  emit("    ' ==================== OUTLINES ====================");
  for (const outline of Object.values(outlines)) {
    if (outline.points.length < 2 || !outline.visible) continue;
    const body = bodies[outline.bodyId];
    if (!body) continue;

    const transform = computeBodyTransform(body, joints);
    const worldPts = outline.points.map((pt) => localToWorld(pt, transform));

    emit(`    ' Outline "${outline.name}" on body "${body.name}" (${worldPts.length} pts)`);
    for (let i = 0; i < worldPts.length; i++) {
      const a = worldPts[i];
      const b = worldPts[(i + 1) % worldPts.length];
      const x1 = a.x * W2M;
      const y1 = -a.y * W2M;
      const x2 = b.x * W2M;
      const y2 = -b.y * W2M;
      emit(`    SketchMgr.CreateLine ${f(x1)}, ${f(y1)}, 0#, ${f(x2)}, ${f(y2)}, 0#`);
    }
  }
  emit('');

  // ==================== SLIDERS (rail lines) ====================
  const sliderArr = Object.values(sliders);
  if (sliderArr.length > 0) {
    emit("    ' ==================== SLIDER RAILS ====================");
    for (const s of sliderArr) {
      const jA = joints[s.jointIdA];
      const jC = joints[s.jointIdC];
      if (!jA || !jC) continue;
      emit(`    SketchMgr.CreateLine ${f(jA.position.x * W2M)}, ${f(-jA.position.y * W2M)}, 0#, ${f(jC.position.x * W2M)}, ${f(-jC.position.y * W2M)}, 0#`);
    }
    emit('');
  }

  // ==================== COLLIDERS (barrier lines) ====================
  const colliderArr = Object.values(colliders);
  if (colliderArr.length > 0) {
    emit("    ' ==================== COLLIDER BARRIERS ====================");
    for (const c of colliderArr) {
      const jA = joints[c.jointIdA];
      const jC = joints[c.jointIdC];
      if (!jA || !jC) continue;
      emit(`    SketchMgr.CreateLine ${f(jA.position.x * W2M)}, ${f(-jA.position.y * W2M)}, 0#, ${f(jC.position.x * W2M)}, ${f(-jC.position.y * W2M)}, 0#`);
    }
    emit('');
  }

  // ==================== CLOSE SKETCH ====================
  emit("    ' Close sketch and zoom to fit");
  emit('    SketchMgr.InsertSketch True');
  emit('    Part.ClearSelection2 True');
  emit('    Part.ViewZoomtofit2');
  emit('');
  emit('    MsgBox "Linkage sketch imported successfully!"');
  emit('End Sub');

  return lines.join('\r\n'); // Windows line endings for VBA
}
